# Generated by Django 5.2.17 on 2026-09-19 20:35

import consent.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0008_subjects_and_person_name_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('wish', models.CharField(choices=[('images_ok', 'Zdjęcia ze mną mogą tu być'), ('no_images', 'Wzmianki tak, zdjęć nie'), ('no_mention', 'Nie chcę być w archiwum')], max_length=12)),
                ('note', models.TextField(blank=True, max_length=1000)),
                ('token', models.CharField(default=consent.models.new_token, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('sent', 'Wysłano link potwierdzający'), ('verified', 'Skrzynka potwierdzona — czeka na administrację'), ('approved', 'Zatwierdzony'), ('rejected', 'Odrzucony'), ('superseded', 'Zastąpiony nowszym'), ('withdrawn', 'Wycofany przez osobę')], default='sent', max_length=12)),
                ('consent_text_version', models.CharField(max_length=20)),
                ('requester_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('requester_user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('previous_consent', models.CharField(blank=True, max_length=10)),
                ('previous_listed', models.BooleanField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('manage_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('manage_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='archive.person')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wniosek osoby',
                'verbose_name_plural': 'wnioski osób',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsentHide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_hides', to='archive.post')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hides', to='consent.personclaim')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='personclaim',
            index=models.Index(fields=['person', 'status'], name='consent_per_person__ab835a_idx'),
        ),
        migrations.AddIndex(
            model_name='personclaim',
            index=models.Index(fields=['email'], name='consent_per_email_3eaf84_idx'),
        ),
        migrations.AddConstraint(
            model_name='consenthide',
            constraint=models.UniqueConstraint(fields=('claim', 'post'), name='one_hide_per_claim_per_post'),
        ),
    ]
