# Generated by Django 5.2.17 on 2026-09-19 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalation',
            options={'ordering': ['-created_at'], 'permissions': [('can_manage_critical_quarantine', 'Może przeglądać i zamykać kwarantannę krytyczną')]},
        ),
        migrations.AddField(
            model_name='escalation',
            name='nask_case_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='escalation',
            name='purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escalation',
            name='reported_to_nask_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escalation',
            name='target_previous_status',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='escalation',
            name='status',
            field=models.CharField(choices=[('pending', 'Czeka na administrację'), ('approved', 'Potwierdzone — do przekazania do NASK'), ('declined', 'Odrzucone przez administrację'), ('purged', 'Przekazane do NASK i trwale usunięte')], default='pending', max_length=8),
        ),
        migrations.CreateModel(
            name='EvidenceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_kind', models.CharField(max_length=16)),
                ('original_post_id', models.PositiveBigIntegerField()),
                ('file_sha256', models.CharField(db_index=True, max_length=64)),
                ('storage_location', models.CharField(blank=True, max_length=300)),
                ('original_name', models.CharField(blank=True, max_length=200)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('uploader_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('uploader_user_agent', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('reported_to_nask_at', models.DateTimeField()),
                ('reported_by_username', models.CharField(blank=True, max_length=150)),
                ('nask_case_reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('escalation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_rows', to='escalation.escalation')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wpis rejestru dowodowego',
                'verbose_name_plural': 'rejestr dowodowy',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
