# Generated by Django 5.2.17 on 2026-09-10 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('format', models.CharField(choices=[('text', 'Tekst / Markdown'), ('latex', 'LaTeX')], default='text', max_length=8)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_messages', to=settings.AUTH_USER_MODEL)),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wiadomość',
                'verbose_name_plural': 'wiadomości',
                'ordering': ['-id'],
            },
        ),
    ]
