# Generated by Django 5.2.17 on 2026-09-15 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('offensive', 'Obraźliwe'), ('illegal', 'Niezgodne z prawem'), ('privacy', 'Dotyczy mnie'), ('other', 'Inne')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('upheld', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='board.message')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reporter__isnull', False)), fields=('message', 'reporter'), name='board_one_report_per_user')],
            },
        ),
    ]
