# Generated by Django 5.2.17 on 2026-09-19 20:29

import archive.models
import archive.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0007_person_directory_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by_username', models.CharField(blank=True, max_length=150)),
                ('file', models.FileField(upload_to=archive.models.attachment_path, validators=[archive.validators.validate_upload])),
                ('original_name', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('source_note', models.CharField(blank=True, max_length=300)),
                ('rights_confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Czeka na moderację'), ('published', 'Opublikowane'), ('rejected', 'Odrzucone'), ('hidden', 'Ukryte')], default='pending', max_length=10)),
                ('review_note', models.TextField(blank=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portraits', to='archive.person')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portraits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortraitAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('publish', 'publikacja'), ('reject', 'odrzucenie'), ('hide', 'ukrycie'), ('restore', 'przywrócenie')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('previous_status', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portrait_actions', to=settings.AUTH_USER_MODEL)),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='portraits.portrait')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PortraitVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='portraits.portrait')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='portrait',
            index=models.Index(fields=['person', 'status'], name='portraits_p_person__015895_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portraitvote',
            unique_together={('portrait', 'user')},
        ),
    ]
