r"""What a link to fuw.lol looks like when somebody pastes it into a chat window.

Every URL on this site is served the same `200.html`: the SPA fills the title in from
JavaScript, and Facebook's scraper — like Messenger's, WhatsApp's, Telegram's, Slack's,
Discord's and Google's — does not run any. So a shared post showed the site's name and
nothing else. This module is the half of the answer that knows the archive: one function
that turns a PATH into the handful of facts a scraper wants.

**It asks the rules; it does not restate them.** `archive.moderation.can_see_post(None,
post)` decides about a post, `archive.people.visible_people(None)` about a person, and
`archive.moderation.visible_posts_q(None)` is the clause every count here is taken over.
A preview that re-derived any of them would be a second, quieter answer to the question
the takedown machinery exists to answer — and the quiet one is the dangerous one, because
a preview is fetched by a robot and then CACHED BY SOMEBODY ELSE for days. A post hidden
at 12:00 whose summary leaked at 11:59 stays readable in a chat window long after the page
itself answers 404. Hence: a pending, hidden, nuked, quarantined or escalated post gets
the generic site card and a 404, exactly like a slug that was never used. The two are
indistinguishable on purpose — `archive/people.py` makes the same trade for somebody who
asked to be taken out of the archive, and for the same reason.

**Nothing from the query string is ever echoed.** `?category=`, `?tag=`, `?person=` and
`?subject=` are looked up, and what goes on the card is the row that came back — never the
string that was typed. A preview is drawn on a stranger's screen with our domain printed
under it, so a page that reflected `?q=` back would let anybody compose a fuw.lol link
whose preview says whatever they like. An unknown slug is a typo: generic card, 404.

**The unit of an answer is `Preview | None`.** `None` means "nothing here that an
anonymous visitor may see", and the view turns every `None` into the same generic card
with a 404 — one refusal, one shape, no branch that can accidentally say more.
"""
import re
from dataclasses import dataclass, replace
from datetime import datetime

from django.conf import settings
from django.db.models import Q

from archive.models import Category, Post, Subject, Tag

# The portrait gallery is a separate app and a separate migration; the archive works
# without it and so does this. Guarded rather than assumed: a deployment that has not
# enabled portraits must still get a person's preview, with the silhouette.
try:
    from portraits.rules import current_portrait
except Exception:  # pragma: no cover - only in a build without the portraits app
    current_portrait = None

SITE_NAME = 'fuw.lol'
LOCALE = 'pl_PL'
# 1200×630 cards generated by `manage.py make_share_images` into frontend/static/, which
# nginx serves from the SPA build root. They are NOT the faculty's 130 px silhouettes:
# Facebook drops any og:image below 200×200, which would mean no picture at all in
# Messenger — the exact client this whole module was written for. The silhouette is inside
# the card instead, on the site's own white/green, so the faculty look survives the floor.
DEFAULT_IMAGE = '/og-default.png'
PERSON_CARDS = {'m': '/og-osoba-m.png', 'f': '/og-osoba-f.png'}
DEFAULT_IMAGE_ALT = 'fuw.lol — archiwum folkloru Wydziału Fizyki UW'
MAX_DESCRIPTION = 200

# Routes that exist but are nobody's shared link: the editor, the account pages, the
# moderation board. They answer 200 (they are real pages; a 404 would be a lie) with the
# generic card and `noindex`, because a login form in Google's index helps nobody.
APP_ROUTES = frozenset({'dodaj', 'edytuj', 'konto', 'logowanie', 'rejestracja', 'moderacja',
                        'eskalacje', 'moje', 'potwierdz', 'tablica'})


@dataclass(frozen=True)
class Preview:
    """The facts a scraper asks for, already resolved and already allowed to be public.

    `image` is absolute or None — a relative og:image is ignored by most scrapers and
    silently by some, which is the worst of the two. `url` is the canonical page a reader
    should land on, never the /share/ path a crawler may have been routed through.
    """
    title: str
    description: str
    url: str
    image: str | None = None
    image_alt: str = DEFAULT_IMAGE_ALT
    type: str = 'website'  # 'article' | 'profile' | 'website'
    published_time: datetime | None = None
    tags: tuple[str, ...] = ()
    noindex: bool = False


# --- absolute URLs ----------------------------------------------------------------------

def site_url() -> str:
    """The origin every canonical URL and every relative image is built from. One setting,
    because a preview that pointed at `localhost` would be cached by Facebook as
    `localhost` for as long as they feel like keeping it."""
    return (getattr(settings, 'FUWLOL_SITE_URL', '') or '').rstrip('/')


def absolute(url: str) -> str | None:
    """'' → None; an R2 URL (already absolute, its own hostname) → itself; `/media/...` →
    the site's own origin in front of it, which is where nginx serves the media volume."""
    url = (url or '').strip()
    if not url:
        return None
    if url.startswith(('http://', 'https://', '//')):
        return url
    return f'{site_url()}/{url.lstrip("/")}'


def canonical(path: str, query: str = '') -> str:
    path = '/' + (path or '').strip('/')
    return f'{site_url()}{path}' + (f'?{query}' if query else '')


# --- Polish, counted ---------------------------------------------------------------------

def plural(n: int, one: str, few: str, many: str) -> str:
    """1 → 'wpis', 2–4 → 'wpisy' (but 12–14 → 'wpisów', like every teen), else 'wpisów'.

    A deliberate mirror of `frontend/src/lib/plural.ts`, which does the same job on the
    page this preview is about — and the two must not drift, or a shared link says
    „3 wpisów" while the page it opens says „3 wpisy". Nine lines is cheaper to keep in
    step than an endpoint that exists to conjugate a noun.
    """
    m10, m100 = n % 10, n % 100
    if n == 1:
        return one
    if 2 <= m10 <= 4 and not 12 <= m100 <= 14:
        return few
    return many


def posts_phrase(n: int) -> str:
    return f'{n} {plural(n, "wpis", "wpisy", "wpisów")}'


# --- text ---------------------------------------------------------------------------------

# The delimiters the corpus actually uses. `auto_summary` (archive/serializers.py) KEEPS
# maths in a summary as `$…$`, because every surface that draws a summary typesets it —
# and a scraper does not. „Zadanie: $\int_0^1 x^2\,dx$" would be pasted into Messenger
# with the dollars showing, so the delimiters come off and the formula text stays: it is
# still the sentence the author wrote, just without the typesetting marks.
_MATH = re.compile(r'\$\$([\s\S]*?)\$\$|\\\[([\s\S]*?)\\\]|\\\(([\s\S]*?)\\\)|\$([^$\n]*)\$')


def strip_math(text: str) -> str:
    def keep(m):
        return ' ' + (m.group(1) or m.group(2) or m.group(3) or m.group(4) or '').strip() + ' '
    return _MATH.sub(keep, text or '')


def clean_text(text: str, limit: int = MAX_DESCRIPTION) -> str:
    """One line, no maths delimiters, no control characters, clipped at a word.

    The control-character pass is not decoration: a description ends up inside a `content="…"`
    attribute, and while escaping stops it breaking out, a raw newline or a bidi override
    inside a meta tag is still a line that renders differently from the text that was
    written. Everything that is not a printable character becomes a space.
    """
    s = strip_math(text)
    s = ''.join(' ' if (ch < ' ' or ch == '\x7f') else ch for ch in s)
    s = re.sub(r'\s+', ' ', s).strip()
    if len(s) <= limit:
        return s
    cut = s[:limit - 1].rstrip()
    if ' ' in cut:
        cut = cut[:cut.rfind(' ')].rstrip()
    return cut.rstrip('.,;:—-') + '…'


# --- what the public may count -------------------------------------------------------------

def public_posts():
    """Every post an anonymous visitor may read, as a queryset — the twin of
    `can_see_post(None, …)` AND `can_read_body(None, …)`, asked rather than rewritten. Every
    count on every card is taken over exactly this, so a hidden, escalated or trusted-only
    post cannot show up as the +1 that says it exists. It is also what the sitemap walks:
    a locked post has nothing to offer a search engine but a title and a name."""
    from archive.moderation import readable_q, visible_posts_q
    return Post.objects.filter(visible_posts_q(None)).filter(readable_q(None))


def _count_for(**filters) -> int:
    return public_posts().filter(**filters).distinct().count()


# --- images ---------------------------------------------------------------------------------

def _attachment_url(att) -> str:
    """The same two-branch answer `AttachmentSerializer.get_url` gives, minus the request:
    an R2 object has an absolute public URL (empty once the object is held or shredded),
    a local file has a `/media/...` path this module absolutises. Keep the two in step —
    the day attachments get a third home, both read the storage the same way."""
    if getattr(att, 'storage_key', ''):
        return att.public_url
    return att.file.url if att.file else ''


def post_image(post):
    """The post's picture: its first image attachment, exactly as `PostListSerializer.get_cover`
    picks the card cover, so a link preview and the site show the same one. None when the
    post has no image, or when its only image is held in quarantine (`public_url` is '' for
    a held object) — the default card then stands in, rather than a URL that 404s."""
    for att in post.attachments.all():
        if att.kind == 'image':
            url = absolute(_attachment_url(att))
            if url:
                return url
    return None


def person_image(person):
    """(url, alt) — the portrait the person's own page shows, or the faculty silhouette.

    `portraits.rules.current_portrait` is the one rule for "which photograph IS this
    person's photograph", and it already answers None while `image_consent` is not
    'granted'. Asking it rather than querying portraits directly is what makes a withdrawn
    consent take the picture out of every future link preview with no second switch to
    remember — art. 81 pr. aut. is not a setting this module gets to have an opinion about.
    """
    portrait = current_portrait(person) if current_portrait else None
    if portrait is not None and getattr(portrait, 'file', None):
        url = absolute(portrait.file.url)
        if url:
            return url, f'{person.full_name} — zdjęcie z galerii archiwum'
    card = PERSON_CARDS.get(person.sex or '', DEFAULT_IMAGE)
    alt = (f'{person.full_name} — sylwetka zastępcza ze spisu osób Wydziału Fizyki UW'
           if card != DEFAULT_IMAGE else DEFAULT_IMAGE_ALT)
    return absolute(card), alt


# --- the cards -------------------------------------------------------------------------------

def generic_preview(url: str | None = None) -> Preview:
    """The site itself — what a scraper gets for the home page, for a page that is nobody's
    link, and for everything we refuse to talk about. The refusal and the front door
    deliberately look identical."""
    return Preview(
        title='fuw.lol — archiwum Wydziału Fizyki UW',
        description='Archiwum folkloru Wydziału Fizyki UW: memy, cytaty z wykładów, legendarne zadania '
                    'egzaminacyjne i kartki z drzwi pracowni. Zbierane i moderowane przez czytelników.',
        url=url or canonical('/'),
        image=absolute(DEFAULT_IMAGE),
        image_alt=DEFAULT_IMAGE_ALT,
        noindex=url is None,
    )


def _home() -> Preview:
    n = public_posts().count()
    return Preview(
        title='fuw.lol — archiwum Wydziału Fizyki UW',
        description=clean_text(
            f'Folklor Wydziału Fizyki UW w jednym miejscu: {posts_phrase(n)} — memy, cytaty z wykładów, '
            'legendarne zadania i kartki z drzwi pracowni. Moderowane, z podaniem źródła.'),
        url=canonical('/'),
        image=absolute(DEFAULT_IMAGE),
    )


def _post(slug: str) -> Preview | None:
    from archive.moderation import can_read_body, can_see_post
    post = (Post.objects.filter(slug=slug)
            .select_related('category').prefetch_related('attachments', 'tags').first())
    # The queryset found it; the rule decides. Both, because a slug in a URL never meets a
    # queryset filter on its own — house rule: visibility is a filter, authority is a check.
    if post is None or not can_see_post(None, post):
        return None
    # A „kontrowersyjny" post is a teaser to a human ON the site, who can read the lock and
    # go and confirm an address. A scraper is neither: the summary it would take is a body
    # excerpt (`auto_summary`) and the picture IS the content, and both land in somebody
    # else's cache and Google's index, where they outlive any later decision to lock or take
    # down. So: the generic card and the 404, exactly as for a hidden post.
    if not can_read_body(None, post):
        return None
    summary = clean_text(post.summary)
    if not summary:
        # Nothing written and nothing derivable (a post that is only a picture). The
        # category and the year are the two things we always know, and they read as a
        # caption rather than as an apology for an empty field.
        bits = [post.category.name]
        if post.year:
            bits.append(f'{"ok. " if post.year_precision == "approx" else ""}{post.year}')
        summary = clean_text(' · '.join(bits) + ' — wpis w archiwum folkloru Wydziału Fizyki UW.')
    image = post_image(post)
    return Preview(
        title=f'{post.title} — fuw.lol',
        description=summary,
        url=canonical(f'/wpis/{post.slug}'),
        image=image or absolute(DEFAULT_IMAGE),
        # A colon, not „quotes": a title is often quoted itself, and „„…"" reads as a typo.
        image_alt=(f'Obraz z wpisu: {post.title}' if image else DEFAULT_IMAGE_ALT),
        type='article',
        published_time=post.published_at,
        tags=tuple(t.name for t in post.tags.all()),
    )


def _person(slug: str) -> Preview | None:
    from archive.people import visible_people
    # `visible_people(None)` — annotated, filed and filtered the way /ludzie is. NOT a bare
    # is_listed filter: somebody named on a post that is still in the moderation queue has
    # no public page yet, and a preview is a public page with a longer memory than most.
    person = visible_people(None).filter(slug=slug).first()
    if person is None:
        return None
    # `post_count` comes with the queryset: `annotate_people` counts distinct posts across
    # BOTH joins (named, and tagged with one of the person's nicknames), which is the
    # number /ludzie prints. Counting again here would be a second answer to a question
    # that already has one, and the two would differ the first time either changed.
    n = person.post_count
    image, alt = person_image(person)
    bits = [b for b in (person.role, person.unit) if b]
    bits.append(f'{posts_phrase(n)} w archiwum')
    return Preview(
        title=f'{person.full_name} — fuw.lol',
        description=clean_text(' · '.join(bits)),
        url=canonical(f'/ludzie/{person.slug}'),
        image=image,
        image_alt=alt,
        type='profile',
    )


def _category(slug: str) -> Preview | None:
    cat = Category.objects.filter(slug=slug).first()
    if cat is None:
        return None
    n = _count_for(category=cat)
    lead = clean_text(cat.description) if cat.description else ''
    tail = f'{posts_phrase(n)} w tej kategorii archiwum folkloru Wydziału Fizyki UW.'
    return Preview(
        title=f'{cat.name} — fuw.lol',
        description=clean_text(f'{lead} {tail}'.strip()),
        url=canonical('/przegladaj', f'category={cat.slug}'),
        image=absolute(DEFAULT_IMAGE),
    )


def _tag(slug: str) -> Preview | None:
    tag = Tag.objects.filter(slug=slug).first()
    if tag is None:
        return None
    n = _count_for(tags=tag)
    if not n:
        # A tag with nothing published under it is not a page — /api/tags/ does not list it
        # either. Refusing here keeps an abandoned nickname from becoming a shareable card.
        return None
    return Preview(
        title=f'#{tag.name} — fuw.lol',
        description=clean_text(f'Wpisy otagowane „{tag.name}”: {posts_phrase(n)}. '
                               'Tagiem chodzi się po archiwum bokiem, nie alfabetycznie.'),
        url=canonical('/przegladaj', f'tag={tag.slug}'),
        image=absolute(DEFAULT_IMAGE),
    )


def _subject(slug: str, *, browse: bool = False) -> Preview | None:
    subject = Subject.objects.filter(slug=slug).first()
    if subject is None:
        return None
    n = _count_for(subjects=subject)
    short = f' ({subject.short})' if subject.short else ''
    return Preview(
        title=f'{subject.name}{short} — fuw.lol',
        description=clean_text(f'{posts_phrase(n)} z tego przedmiotu. Roku nikt nie pamięta; '
                               'wszyscy pamiętają, że to było na tych zajęciach.'),
        url=(canonical('/przegladaj', f'subject={subject.slug}') if browse
             else canonical(f'/przedmioty/{subject.slug}')),
        image=absolute(DEFAULT_IMAGE),
    )


def _browse(query) -> Preview | None:
    """/przegladaj, with or without a filter. Exactly one filter is resolved — the first
    one present, in the order the page itself applies them — and an unknown slug is a 404
    rather than an empty page with a card, so a mistyped link cannot be dressed up as one
    of ours."""
    for key, resolve in (('category', _category), ('tag', _tag),
                         ('person', _person_browse), ('subject', _subject_browse)):
        value = _first(query, key)
        if value:
            return resolve(value)
    n = public_posts().count()
    return Preview(
        title='Przeglądaj archiwum — fuw.lol',
        description=clean_text(f'Wszystkie wpisy archiwum: {posts_phrase(n)}. Filtruj po kategorii, '
                               'osobie, przedmiocie albo tagu; szukaj też w LaTeX-u.'),
        url=canonical('/przegladaj'),
        image=absolute(DEFAULT_IMAGE),
    )


def _person_browse(slug: str) -> Preview | None:
    """`?person=` is the same person, seen from the browse page: one card, one canonical
    URL. The canonical is the browse URL that was actually shared rather than the profile,
    because a shared link must open what the sharer saw."""
    preview = _person(slug)
    if preview is None:
        return None
    return replace(preview, url=canonical('/przegladaj', f'person={slug}'))


def _subject_browse(slug: str) -> Preview | None:
    return _subject(slug, browse=True)


def _people_index() -> Preview:
    from archive.people import visible_people
    n = visible_people(None).count()
    return Preview(
        title='Osoby — fuw.lol',
        description=clean_text(f'Spis osób, o których mówi folklor Wydziału: {n} '
                               f'{plural(n, "osoba", "osoby", "osób")}. Ułożony jak wydziałowy spis osób, '
                               'bo stamtąd jest przepisany — z ksywkami zamiast numeru pokoju.'),
        url=canonical('/ludzie'),
        image=absolute(DEFAULT_IMAGE),
    )


def listed_subjects():
    """The rows /przedmioty actually shows: everything from the Faculty's programme
    (`created_by` NULL — an OFFER, listed whether or not anybody has written about it yet)
    plus the ones a user named that have a published post behind them.

    The same rule as `archive.views.SubjectViewSet.get_queryset` for the list action, and
    the one rule in this module that is restated rather than imported — it lives inside a
    viewset, which cannot be asked without an HTTP request around it. The half that decides
    what „published" means is still borrowed (`public_posts`), so the part that could leak
    is single-sourced and only the "a programme row is always listed" half is repeated.
    """
    return Subject.objects.filter(Q(created_by__isnull=True) | Q(posts__in=public_posts())).distinct()


def _subjects_index() -> Preview:
    n = listed_subjects().count()
    return Preview(
        title='Przedmioty — fuw.lol',
        description=clean_text(f'Archiwum poukładane według przedmiotów z programu studiów: {n} '
                               f'{plural(n, "przedmiot", "przedmioty", "przedmiotów")} — od analizy '
                               'po II Pracownię.'),
        url=canonical('/przedmioty'),
        image=absolute(DEFAULT_IMAGE),
    )


# The standing pages: copy that does not depend on a row in the database. Kept as data
# rather than as nine functions, because nine functions that differ only in two strings
# are nine places to forget a change.
STANDING = {
    '/os-czasu': ('Oś czasu — fuw.lol',
                  'Maszyna czasu Wydziału: strona fuw.edu.pl z dowolnego dnia od 1998 r. prosto z '
                  'Internet Archive, a wcześniej — gazeta, Kopernik i dinozaury. UW istnieje od 1816 r.'),
    '/czat': ('Czat — fuw.lol',
              'Shoutbox jak z 2005 roku: piszą wszyscy, także bez konta. 2048 znaków, LaTeX tak, '
              'obrazki nie, moderacja jak wszędzie indziej.'),
    '/o-archiwum': ('O archiwum — fuw.lol',
                    'Po co to jest, co wolno wrzucić (art. 29¹ i art. 81 pr. aut.), jak zgłosić wpis '
                    'do usunięcia i kto o tym decyduje. Regulamin bez prawniczej mgły.'),
    '/ludzie/zgoda': ('Zgoda na wizerunek — fuw.lol',
                      'Co znaczy ✓ przy nazwisku: ta osoba sama potwierdziła zgodę na publikację '
                      'wizerunku (art. 81 pr. aut.). Bez niej nie ma galerii zdjęć — i tyle.'),
}
# A random post is a different post every time it is opened, so it is not a page anybody
# should index or cache a card for; it still gets a card, because people do share it.
RANDOM_PAGE = ('Losowy wpis — fuw.lol',
               'Jeden wpis z archiwum, wybrany losowo. Zasada nieoznaczoności w wersji użytkowej: '
               'zanim klikniesz, jest wszystkim naraz.')


# --- the dispatcher ------------------------------------------------------------------------

def _first(query, key: str) -> str:
    """One value for `key`, from a QueryDict, a plain dict, or a dict of lists. Trimmed,
    and short: a slug is at most 120 characters in this schema, and anything longer is
    somebody probing, not somebody sharing."""
    if not query:
        return ''
    value = query.get(key, '')
    if isinstance(value, (list, tuple)):
        value = value[0] if value else ''
    return str(value or '').strip()[:160]


def normalise_path(path: str) -> str:
    """'/wpis/x/' and '//wpis//x' → '/wpis/x'. Collapsing the slashes is not tidiness: the
    path is pasted into the canonical URL, and `https://fuw.lol` + `//example.com/` reads
    as somebody else's host to a human skimming the preview."""
    path = re.sub(r'/{2,}', '/', '/' + (path or '').strip())
    return '/' + path.strip('/')


def preview_for(path: str, query=None) -> Preview | None:
    """The one entry point. `path` is the SPA route a reader would type, with or without
    the trailing slash; `query` is anything with a `.get` (`request.GET` in the view).

    Returns None for everything an anonymous visitor may not see, for a slug that does not
    resolve, and for a path this site does not serve — one value for three refusals,
    because the whole point is that a scraper cannot tell them apart.
    """
    path = normalise_path(path)
    segments = [s for s in path.split('/') if s]

    if not segments:
        return _home()
    if path in STANDING:
        title, description = STANDING[path]
        return Preview(title=title, description=clean_text(description),
                       url=canonical(path), image=absolute(DEFAULT_IMAGE))
    if path == '/losowe':
        title, description = RANDOM_PAGE
        return Preview(title=title, description=clean_text(description),
                       url=canonical(path), image=absolute(DEFAULT_IMAGE), noindex=True)
    if segments[0] in APP_ROUTES:
        return replace(generic_preview(canonical(path)), noindex=True)

    head = segments[0]
    if head == 'wpis' and len(segments) == 2:
        return _post(segments[1])
    if head == 'przegladaj' and len(segments) == 1:
        return _browse(query)
    if head == 'ludzie':
        if len(segments) == 1:
            return _people_index()
        if len(segments) == 2:
            return _person(segments[1])
        # /ludzie/<slug>/{potwierdz,ustawienia} — a person's own forms, reached from a
        # mail rather than shared — and /ludzie/zgoda/podglad, the badge demo.
        if len(segments) == 3 and segments[2] in ('potwierdz', 'ustawienia', 'podglad'):
            return replace(generic_preview(canonical(path)), noindex=True)
        return None
    if head == 'przedmioty':
        if len(segments) == 1:
            return _subjects_index()
        if len(segments) == 2:
            return _subject(segments[1])
        return None
    return None
