# Generated by Django 5.2.17 on 2026-10-06 08:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('locale', models.CharField(max_length=8)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('document', models.JSONField()),
                ('document_version', models.CharField(default='medapp.export/2', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('published', 'Opublikowany'), ('retired', 'Wycofany')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wum_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'szablon pacjenta',
                'verbose_name_plural': 'szablony pacjentów',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WumProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('surname', models.CharField(blank=True, max_length=80)),
                ('contact_email', models.EmailField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('agreed_text_version', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wum_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'konto WUM',
                'verbose_name_plural': 'konta WUM',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payload', models.JSONField()),
                ('payload_version', models.CharField(max_length=30)),
                ('consent_text_version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('published', 'Opublikowana'), ('withdrawn', 'Wycofana przez osobę'), ('superseded', 'Zastąpiona nowszą')], default='published', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wum_publications', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wum.publication')),
            ],
            options={
                'verbose_name': 'publikacja',
                'verbose_name_plural': 'publikacje',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='wum_pub_status_recent'), models.Index(fields=['account', 'status'], name='wum_pub_account_status')],
            },
        ),
    ]
