# Generated by Django 5.2.17 on 2026-10-07 18:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(max_length=80)),
                ('profession', models.CharField(choices=[('physiotherapist', 'Fizjoterapeuta / fizjoterapeutka'), ('dietitian', 'Dietetyk / dietetyczka'), ('psychologist', 'Psycholog / psycholożka'), ('nurse', 'Pielęgniarz / pielęgniarka'), ('other', 'Inny zawód')], max_length=20)),
                ('about', models.CharField(blank=True, max_length=600)),
                ('listed', models.BooleanField(default=False)),
                ('slot_minutes', models.PositiveSmallIntegerField(default=45)),
                ('hours', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wum_practice', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'gabinet',
                'verbose_name_plural': 'gabinety',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('requested', 'Zgłoszona'), ('confirmed', 'Potwierdzona'), ('declined', 'Odrzucona'), ('cancelled', 'Odwołana'), ('completed', 'Odbyta'), ('no_show', 'Nieobecność')], default='requested', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_by', models.CharField(choices=[('patient', 'pacjent'), ('practitioner', 'gabinet')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wum_visits', to=settings.AUTH_USER_MODEL)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='wum.practice')),
            ],
            options={
                'verbose_name': 'wizyta',
                'verbose_name_plural': 'wizyty',
                'ordering': ['start', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PracticeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('body', models.TextField()),
                ('shared_with_patient', models.BooleanField(default=False)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amends', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amended_by', to='wum.practicenote')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wum_practice_notes', to=settings.AUTH_USER_MODEL)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='wum.practice')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='wum.visit')),
            ],
            options={
                'verbose_name': 'notatka gabinetu',
                'verbose_name_plural': 'notatki gabinetu',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['practice', 'start'], name='wum_visit_practice_start'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient', 'start'], name='wum_visit_patient_start'),
        ),
        migrations.AddIndex(
            model_name='practicenote',
            index=models.Index(fields=['practice', 'patient', '-created_at'], name='wum_note_practice_patient'),
        ),
    ]
