# Generated by Django 5.2.17 on 2026-09-10 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='moderation',
            field=models.CharField(choices=[('visible', 'Widoczny'), ('hidden', 'Ukryty'), ('nuked', 'Ukryty nuklearnie')], default='visible', max_length=8),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'Czeka na moderację'), ('published', 'Opublikowany'), ('rejected', 'Odrzucony'), ('hidden', 'Ukryty'), ('nuked', 'Ukryty nuklearnie')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('hide', 'ukrycie'), ('restore', 'przywrócenie'), ('nuke', 'ukrycie nuklearne'), ('unnuke', 'przywrócenie po opcji nuklearnej'), ('publish', 'publikacja'), ('reject', 'odrzucenie')], max_length=8)),
                ('reason', models.TextField(blank=True)),
                ('previous_status', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='archive.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='archive.post')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
