# Generated by Django 5.2.17 on 2026-09-19 10:21

import archive.models
import archive.validators
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_search_rights_good_faith'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'base_manager_name': 'all_objects', 'ordering': ['-published_at', '-created_at']},
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attachment',
            name='sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='attachment',
            name='size_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attachment',
            name='storage_key',
            field=models.CharField(blank=True, db_index=True, max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='submitter_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='submitter_user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, upload_to=archive.models.attachment_path, validators=[archive.validators.validate_upload]),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='action',
            field=models.CharField(choices=[('hide', 'ukrycie'), ('restore', 'przywrócenie'), ('nuke', 'ukrycie nuklearne'), ('unnuke', 'przywrócenie po opcji nuklearnej'), ('publish', 'publikacja'), ('reject', 'odrzucenie'), ('quarantine', 'kwarantanna krytyczna'), ('purge', 'trwałe usunięcie po zgłoszeniu do NASK')], max_length=12),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='previous_status',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'Czeka na moderację'), ('published', 'Opublikowany'), ('rejected', 'Odrzucony'), ('hidden', 'Ukryty'), ('nuked', 'Ukryty nuklearnie'), ('quarantined', 'Kwarantanna krytyczna'), ('purged', 'Usunięty trwale')], default='pending', max_length=16),
        ),
    ]
