# Generated by Django 5.2.17 on 2026-09-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_alter_post_options_alter_post_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationaction',
            name='action',
            field=models.CharField(choices=[('hide', 'ukrycie'), ('restore', 'przywrócenie'), ('nuke', 'ukrycie nuklearne'), ('unnuke', 'przywrócenie po opcji nuklearnej'), ('publish', 'publikacja'), ('reject', 'odrzucenie'), ('quarantine', 'kwarantanna krytyczna'), ('purge', 'trwałe usunięcie po zgłoszeniu do NASK'), ('feature', 'wyróżnienie'), ('unfeature', 'cofnięcie wyróżnienia')], max_length=12),
        ),
    ]
