# Generated by Django 5.2.17 on 2026-09-19 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_alter_moderationaction_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_by_username', models.CharField(blank=True, max_length=150)),
                ('changes', models.JSONField()),
                ('base', models.JSONField()),
                ('rationale', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Czeka'), ('accepted', 'Przyjęta'), ('rejected', 'Odrzucona'), ('withdrawn', 'Wycofana')], default='pending', max_length=10)),
                ('decision_note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_suggestions', to='archive.post')),
                ('suggested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PostRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('changed_by_username', models.CharField(blank=True, max_length=150)),
                ('source', models.CharField(choices=[('author', 'edycja autora'), ('moderator', 'edycja moderacji'), ('suggestion', 'przyjęta poprawka')], default='author', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='archive.post')),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='archive.editsuggestion')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='editsuggestion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('post', 'suggested_by'), name='one_pending_suggestion_per_person_per_post'),
        ),
    ]
