# Generated by Django 5.2.17 on 2026-09-19 20:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from archive.people import derive_surname, sort_key_for, split_degree


def file_existing_people(apps, schema_editor):
    """Rows created before the directory fields existed carry the title inside `name`
    ("dr Kwant Niepewny"). Peel it into `degree` and fill the filing keys the same way
    Person.save() will from now on. Pure functions from archive/people.py; a no-op on a
    name that has no title."""
    Person = apps.get_model('archive', 'Person')
    for person in Person.objects.all():
        degree, rest = split_degree(person.name)
        if degree and not person.degree:
            person.degree, person.name = degree, rest
        if not person.surname:
            person.surname = derive_surname(person.name)
        person.sort_key = sort_key_for(person.surname, person.name)
        person.save(update_fields=['degree', 'name', 'surname', 'sort_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_editsuggestion_postrevision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['sort_key', 'name']},
        ),
        migrations.AddField(
            model_name='person',
            name='aliases',
            field=models.ManyToManyField(blank=True, help_text='ksywki — wpis otagowany ksywką jest wpisem tej osoby', related_name='alias_of', to='archive.tag'),
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='degree',
            field=models.CharField(blank=True, help_text='tytuł/stopień, jak w spisie osób: dr, prof. dr hab., mgr inż.', max_length=40),
        ),
        migrations.AddField(
            model_name='person',
            name='image_consent',
            field=models.CharField(choices=[('unknown', 'nieznana'), ('granted', 'wyrażona'), ('refused', 'odmówiona — bez zdjęć'), ('opted_out', 'wycofana — poza archiwum')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(blank=True, choices=[('', 'nie podano'), ('m', 'mężczyzna'), ('f', 'kobieta')], default='', help_text='tylko po to, by dobrać sylwetkę zastępczą ze spisu osób', max_length=1),
        ),
        migrations.AddField(
            model_name='person',
            name='sort_key',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, help_text='do sortowania i litery w spisie; puste = ostatni wyraz nazwy', max_length=80),
        ),
        migrations.AddField(
            model_name='person',
            name='unit',
            field=models.CharField(blank=True, help_text='jednostka, jak w spisie: „Instytut Fizyki Teoretycznej, Katedra…”', max_length=160),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='bez tytułu — ten idzie do osobnego pola', max_length=120),
        ),
        migrations.RunPython(file_existing_people, migrations.RunPython.noop),
    ]
