# Generated by Django 5.2.17 on 2026-09-19 20:33
"""Two new axes' worth of schema, and the two data steps that make them true on day one.

`Subject` arrives seeded from the Faculty's own first- and second-cycle physics programmes
(m.fuw.edu.pl, the „Materiały dydaktyczne" pages for I/II/III rok and studia II stopnia,
read September 2026). Seeding it rather than starting empty is the whole difference between
a picker that suggests „Elektrodynamika klasyczna" and a picker that suggests nothing and
thereby collects thirty spellings of it. These are course names, not people: no consent
question arises, and printing the real ones is what makes the archive legible to somebody
who sat them.

`Person.name_key` is the folded name that makes "this person already exists" answerable
when somebody types a name instead of picking one. Existing rows are filled here with the
same fold `Person.save()` will use from now on — the alternative, filling it lazily on next
save, would let a duplicate be created in the window before anybody edits the old row.
"""

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from archive.search import normalize_text
from archive.subjects import subject_slug


# (name, short, order) — the order is the year it is usually sat in, so the list reads like
# a programme rather than an alphabet. Gaps of 10 leave room for whatever the Faculty adds.
SUBJECTS = [
    # I rok
    ('Fizyka elementarna', 'FE', 10),
    ('Mechanika', 'Mech.', 20),
    ('Elektryczność i magnetyzm', 'E i M', 30),
    ('Analiza matematyczna I', 'AM1', 40),
    ('Analiza matematyczna II', 'AM2', 50),
    ('Algebra z geometrią', 'AzG', 60),
    ('Analiza niepewności pomiarowych', 'ANP', 70),
    ('Pracownia wstępna', 'Prac. wst.', 80),
    ('Programowanie', 'Prog.', 90),
    ('Szkolenie BHP', 'BHP', 100),
    # II rok
    ('Drgania i fale', 'D i F', 110),
    ('Szczególna teoria względności', 'STW', 120),
    ('Wstęp do fizyki kwantowej i budowy materii', 'WFK', 130),
    ('Mechanika klasyczna', 'MK', 140),
    ('Analiza matematyczna III', 'AM3', 150),
    ('Metody matematyczne fizyki', 'MMF', 160),
    ('I Pracownia fizyczna', 'I Prac.', 170),
    ('Pracownia elektroniczna', 'Prac. el.', 180),
    # III rok
    ('Mechanika kwantowa I', 'MQ1', 190),
    ('Termodynamika fenomenologiczna', 'Termo', 200),
    ('Elektrodynamika klasyczna', 'Elektro', 210),
    ('Wstęp do optyki i fizyki ciała stałego', 'Optyka', 220),
    ('Elementy fizyki jądrowej', 'FJ', 230),
    ('Elementy fizyki cząstek elementarnych', 'FCE', 240),
    ('Metody numeryczne', 'MN', 250),
    ('II Pracownia fizyczna', 'II Prac.', 260),
    ('Astronomia ogólna', 'Astro', 270),
    ('Proseminarium licencjackie', 'Prosem.', 280),
    # studia II stopnia
    ('Mechanika kwantowa II', 'MQ2', 290),
    ('Fizyka statystyczna', 'FS', 300),
    ('Kwantowa teoria pola', 'QTP', 310),
    ('Fizyka ciała stałego', 'FCS', 320),
    ('Elektrodynamika ośrodków materialnych', 'EOM', 330),
    ('Mechanika ośrodków ciągłych', 'MOC', 340),
    ('Teoria grup', 'TG', 350),
]


def seed_subjects(apps, schema_editor):
    """`created_by` stays NULL on every one of these, which is what tells the API they came
    from the programme and are listed whether or not anybody has posted about them yet.
    Slugs come from `subjects.subject_slug`, the same function the write path folds a typed
    name with — so „Fizyka ciała stałego" typed in the editor lands on this row rather than
    minting a second one."""
    Subject = apps.get_model('archive', 'Subject')
    for name, short, order in SUBJECTS:
        Subject.objects.get_or_create(slug=subject_slug(name),
                                      defaults={'name': name, 'short': short, 'order': order})


def unseed_subjects(apps, schema_editor):
    """Reverse: only the seeded rows, and only the ones nobody has filed a post under —
    a reversal that took somebody's posts off their course would be a data loss dressed
    up as a rollback."""
    Subject = apps.get_model('archive', 'Subject')
    slugs = [subject_slug(name) for name, _, _ in SUBJECTS]
    for subject in Subject.objects.filter(slug__in=slugs, created_by__isnull=True):
        if not subject.posts.exists():
            subject.delete()


def fill_name_keys(apps, schema_editor):
    """The same fold `Person.save()` applies from now on. `update()` per row rather than
    `save()`: the historical model has no `save()` override to call, and the key is derived
    from `name` alone, so there is nothing else to keep in step."""
    Person = apps.get_model('archive', 'Person')
    for person in Person.objects.all():
        Person.objects.filter(pk=person.pk).update(name_key=normalize_text(person.name)[:160])


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_person_directory_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name_key',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=160),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('short', models.CharField(blank=True, help_text='skrót, jakim mówi o przedmiocie rocznik: AM1, MK, II Prac.', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='kolejność w spisie; seed numeruje wg roku studiów')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, help_text='puste = przedmiot z programu studiów (seed/admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='posts', to='archive.subject'),
        ),
        migrations.RunPython(seed_subjects, unseed_subjects),
        migrations.RunPython(fill_name_keys, migrations.RunPython.noop),
    ]
