# Generated by Django 5.2.17 on 2026-09-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """„Kontrowersyjne": content for the trusted tier, the post itself still listed.

    No back-fill, deliberately — `False` is right for every existing row. Inferring a lock
    from a category, a report or a hide would be inventing a moderation decision nobody
    made, and this field only ever takes reach away. No index either: a boolean skewed ~99/1
    is not selective and never stands alone in a query (`featured` carries none for the same
    reason)."""

    dependencies = [
        ('archive', '0008_subjects_and_person_name_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trusted_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='action',
            field=models.CharField(choices=[('hide', 'ukrycie'), ('restore', 'przywrócenie'), ('nuke', 'ukrycie nuklearne'), ('unnuke', 'przywrócenie po opcji nuklearnej'), ('publish', 'publikacja'), ('reject', 'odrzucenie'), ('quarantine', 'kwarantanna krytyczna'), ('purge', 'trwałe usunięcie po zgłoszeniu do NASK'), ('feature', 'wyróżnienie'), ('unfeature', 'cofnięcie wyróżnienia'), ('lock', 'ograniczenie do zweryfikowanych'), ('unlock', 'zdjęcie ograniczenia')], max_length=12),
        ),
    ]
