# Generated by Django 5.2.17 on 2026-09-26 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[('skoki', 'MedApp (skoki)')], default='skoki', max_length=20)),
                ('kind', models.CharField(choices=[('bug', 'Błąd'), ('suggestion', 'Sugestia'), ('idea', 'Pomysł'), ('comment', 'Komentarz')], max_length=10)),
                ('text', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('locale', models.CharField(blank=True, max_length=8)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('new', 'Nowa'), ('triaged', 'Przejrzana'), ('done', 'Załatwiona'), ('spam', 'Spam')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'uwaga',
                'verbose_name_plural': 'uwagi',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['status', '-id'], name='feedback_status_recent'), models.Index(fields=['location'], name='feedback_location')],
            },
        ),
    ]
